const path = require('path')
const fs = require('fs-extra')

// const rimraf = require('rimraf')
const ROOT_DIR = path.resolve(__dirname, '..')
const SRC_DIR = path.resolve(ROOT_DIR, 'src')
const API_DIR = path.resolve(SRC_DIR, 'routes/api')

const ASSETS_LIST_FILE = path.resolve(SRC_DIR, 'shaders-list.js')

function walk(src) {
  if (fs.lstatSync(src).isFile()) return [src]
  const entries = fs.readdirSync(src)
  return entries.flatMap((entry) => walk(path.resolve(src, entry)))
}

console.log('')
// REMOVE ALL NON glsl files

const apis = walk(API_DIR)
  .filter((file) => file.endsWith('.js'))
  .map((file) => path.relative(API_DIR, file))
  .map((file) => file.replace('.js', ''))
  .map((file) => {
    if (file.endsWith('/index')) {
      const src = file.replace('/index', '')
      console.log('✅', file, '->', src)
      return src
    } else {
      console.log('✅', file)
      return file
    }
  })

const jsFileContent = `/*
This file has been generated by ${path.relative(ROOT_DIR, __filename)}
DO NOT MODIFY.

After adding or renaming js files in ${path.relative(ROOT_DIR, API_DIR)}, 
please run yarn create:assets to update this list
*/

export default ${JSON.stringify(apis, null, 2)};
`

console.log(`\n✅ Creating ${path.relative(ROOT_DIR, ASSETS_LIST_FILE)} ...`)
fs.writeFileSync(ASSETS_LIST_FILE, jsFileContent, { encoding: 'utf-8' })
