/*
This file has been generated by scripts/create-assets.js
DO NOT MODIFY.

After adding or renaming js files in src/routes/api, 
please run yarn create:assets to update this list
*/

export default [
  "basic/centered-circle",
  "chromatic-aberration/circle-motion-blur",
  "chromatic-aberration/circle",
  "chromatic-aberration/circles",
  "chromatic-aberration/circles/motion-blur",
  "chromatic-aberration/liquid-distortion",
  "math/impulse-function",
  "noise/noise-1",
  "noise/noise-2"
];
